#!/bin/bash

#
# Make a new THREE.js sketch, joining passed arguments as title.
#

# Settings from https://sipb.mit.edu/doc/safe-shell/
# -e          = exit on error
# -u          = unset is an error
# -o pipefail = pipelines to produce a failure return code if any command errors;
#               normally, pipelines only return a failure if the last command errors.
set -eu -o pipefail

# get slug
title="$*"
if [ ${#title} -eq 0 ]; then
    echo "usage: ,3js [Title of sketch]"
    exit 1
fi
slug=$(,slugify $title)

# settings. lack of / on `template` intentional for `cp`
dir=~/repos/3js-experiments/src/
template=~/repos/3js-experiments/src/00-template
to_open=~/repos/3js-experiments/index.html
to_open_tmp=~/repos/3js-experiments/index.tmp.html

# find existing files to get number
existing=$(ls ${dir})
highest="0"
for e in ${existing[@]}; do
    num=$(echo ${e} | cut -d'-' -f1 | sed 's/^0*//')
    if [[ ${num} -gt ${highest} ]]; then
        highest=${num}
    fi
done
new_num=$(echo "${highest} + 1" | bc | xargs printf "%02d")

# calculate new path
new_path=${dir}${new_num}-${slug}

# copy over
echo "Making new 3js experiment at ${new_path}"
cp -R ${template} ${new_path}

# TODO: do this elegantly by looking up that one program where you don't have to make a
# tempfile
# Eit the index.html file.
# Comment out all dist ones
cat ${to_open} | sed -E 's/^ *(<script.*dist.*)/  <!-- \1 -->/' > ${to_open_tmp}
# next, append new one at end
cat ${to_open_tmp} | sed -E "s/<\/head>/  <script defer src=\"dist\/${new_num}-${slug}.js\"><\/script>\n<\/head>/" > ${to_open}
rm ${to_open_tmp}

# Open file for editing
code ${new_path}/index.ts

# If server is running, open page; if not, start server (which auto opens page)
cd ~/repos/3js-experiments/
if lsof -i :8080 -P -n | grep LISTEN > /dev/null; then
    open -u http://localhost:8080
else
    npm run serve:dev
fi
