#!/bin/bash

#
# Make a new note in the garage, joining passed arguments as title.
#

# Settings from https://sipb.mit.edu/doc/safe-shell/
# -e          = exit on error
# -u          = unset is an error
# -o pipefail = pipelines to produce a failure return code if any command errors;
#               normally, pipelines only return a failure if the last command errors.
set -eu -o pipefail

title="$*"

if [ ${#title} -eq 0 ]; then
    echo "usage: ,note [Title of note]"
    exit 1
fi

slug=$(,slugify $title)
path=~/repos/website-3/posts/garage/${slug}.md

if [[ -f ${path} ]]; then
    echo ",note: Error: File exits: ${path}"
    exit 1
fi

# If title contains a : in it, front matter (YAML?) needs quote escaping.
if [[ "${title}" == *":"* ]]; then
    title="\"${title}\""
fi
d=$(date +"%Y-%m-%d")

cat > ${path} <<- EOF
---
title: ${title}
date: ${d}
---

EOF

code ${path}
