#!/bin/bash

#
# Make a new jekyll post, joining passed arguments as title.
#

# Settings from https://sipb.mit.edu/doc/safe-shell/
# -e          = exit on error
# -u          = unset is an error
# -o pipefail = pipelines to produce a failure return code if any command errors;
#               normally, pipelines only return a failure if the last command errors.
set -eu -o pipefail

title="$*"

if [ ${#title} -eq 0 ]; then
    echo "usage: ,post [Title of post]"
    exit 1
fi

slug=$(,slugify $title)
day=$(date +%Y-%m-%d)
path=~/repos/website/_posts/${day}-${slug}.md

if [[ -f ${path} ]]; then
    echo ",post: Error: File exits: ${path}"
    exit 1
fi

# If title contains a : in it, front matter (YAML?) needs quote escaping.
if [[ "${title}" == *":"* ]]; then
    title="\"${title}\""
fi
d=$(date +"%Y-%m-%d %H:%M %z")

cat > ${path} <<- EOF
---
title: ${title}
subtitle: TBD
date: ${d}
category: Writing
tag: TBD "Creating & Thinking" Design Health Programming
image: /data/${slug}/TBD.jpg
---

EOF

code ${path}
